SELECT * FROM GELEC.ED_DOCUMENTOS WHERE NRO_DOCUMENTO='D-22-11-040340';
SELECT * FROM GELEC.ED_DET_DOCUMENTOS_CLIENTES WHERE ID_DOCUMENTO=10613323;
select * from gelec.ed_reclamos where id_documento=10613323;


SELECT 
    D.ID_DOCUMENTO,
    D.NRO_DOCUMENTO,
    DC.CUENTA,
    (SELECT COUNT(1) FROM GELEC.ED_RECLAMOS WHERE ID_DOCUMENTO=D.ID_DOCUMENTO AND CUENTA=DC.CUENTA) RECLAMOS,
    DC.ESTADO_CLIE,
    DC.FECHA_INICIO_CORTE, 
    DC.FECHA_FIN_CORTE
FROM 
    GELEC.ED_DOCUMENTOS D,
    GELEC.ED_DET_DOCUMENTOS_CLIENTES DC
WHERE 
    d.id_documento=dc.id_documento
    and DC.FECHA_FIN_CORTE IS NOT NULL 
    AND DC.LOG_HASTA IS NULL
    AND NVL(D.LOG_HASTA,0)=0
    and dc.estado_clie not in('Normalizado', 'Cancelado')
;

