SELECT * FROM NEXUS_GIS.SPRCLIENTINTERFACE;

SELECT * FROM NEXUS_GIS.SPRCLIENTINTERFACE X
WHERE 
CLIENTID IN (SELECT CLIE_ID FROM UTC.CLIENTES)
AND (SELECT LOGIDTO FROM NEXUS_GIS.SPRCLIENTS WHERE FSCLIENTID=X.CLIENTID)=0
;

SELECT 
    UC.ID, 
    UC.CLIE_ID, 
    UC.CLIE_TELEFONO, 
    LENGTH(UC.CLIE_TELEFONO) LARGO
FROM UTC.CLIENTES UC
WHERE
  ROWNUM<50
  AND (SELECT LOGIDTO FROM NEXUS_GIS.SPRCLIENTS WHERE FSCLIENTID=UC.CLIE_ID)=0
--  AND CLIE_TELEFONO IS NULL
  AND CLIE_ID='6773413862'
;
--6773413862
--UPDATE UTC.CLIENTES SET CLIE_TELEFONO='ABCDEFGHIJKLMNÑOPQRSTUVWXYZ' WHERE CLIE_ID='6773413862';


SELECT CLIENTID, TELEPHONENUMBER FROM NEXUS_GIS.SPRCLIENTINTERFACE
WHERE CLIENTID='6773413862'
;



           SELECT distinct(ident) ident
             FROM utc.utc_novedades
            WHERE LOGID = 0 AND IDENT IS NOT NULL
         ORDER BY ident;

        SELECT TARI_ID,CICL_ID,RUTA_ID,CLIE_APYNOM,CLIE_POT_CONV_PTA,CLIE_POT_CONV_FPTA,
               TMED_ID,CLIE_MEDIDOR_NUM,CLIE_CALLE_NUM,ACTI_ID,CLIE_TELEFONO,CLIE_COMERCIAL_ALTA,
               CLIE_COMERCIAL_BAJA,CLIE_DOMICILIO_PISO,CLIE_DOMICILIO_DEPTO,CLIE_LOCALIDAD,
               ACU_SRV_ESTADO,CLIE_POSTAL_COD,TDOC_ID,CLIE_DOCUM_NUM,OFCO_ID,TENS_ID,CLIE_GESTOR_NOMBRE,
               CLIE_GESTOR_TELEFONO,CLIE_TRATO_ESPECIAL,CLIE_NEXUS_ID,TARIFA_ENRE,CLIE_FASES,CUENTA_BIG,
               CLIE_ENTRE_CALLE1,CLIE_ENTRE_CALLE2,TIAS_ID
           FROM UTC.CLIENTES
          WHERE CLIE_ID = P_IDENT;