SELECT * FROM GELEC.ED_DOCUMENTOS;
SELECT * FROM ALL_TABLES WHERE OWNER='GELEC' AND TABLE_NAME LIKE '%TIPO%';
SELECT * FROM GELEC.ED_RECLAMOS;
SELECT * FROM GELEC.ED_TIPO_RECLAMO;

SELECT 
    D.NRO_DOCUMENTO AS NRODOCUMENTO, 
    (SELECT TIPO_CORTE FROM GELEC.ED_DOCUMENTOS WHERE ID_DOCUMENTO=R.ID_DOCUMENTO) TIPO_CORTE,
    R.CUENTA, 
    R.NOMBRE, 
    (SELECT DESCRIPTION FROM GELEC.ED_TIPO_RECLAMO WHERE ID=R.ID_TIPO_RECLAMO) TIPO_RECLAMO,
    R.DESCRIPCION,
    R.FECHA_CREACION_CLIENTE AS FECHA, 
    NVL(R.REITERACIONES,0) AS REITERACIONES,
    R.ULTIMA_REITERACION AS ULTIMAREITERACION, 
    R.FECHA_CIERRE AS FECHAFINRECLAMO, 
    D.REGION, 
    D.ZONA, 
    D.PARTIDO, 
    D.LOCALIDAD,   
    (SELECT COUNT(*) FROM GELEC.ED_CLIENTE_NOTA CN INNER JOIN GELEC.ED_NOTAS N ON N.ID_NOTA = CN.ID_NOTA WHERE CN.CUENTA = R.CUENTA  AND CN.ID_DOCUMENTO = R.ID_DOCUMENTO AND N.ID_TIPO_NOTA = 4 AND N.EFECTIVO IS NOT NULL) AS LLAMADAS, 
    (SELECT COUNT(*) FROM GELEC.ED_CLIENTE_NOTA CN INNER JOIN GELEC.ED_NOTAS N ON N.ID_NOTA = CN.ID_NOTA WHERE CN.CUENTA = R.CUENTA  AND CN.ID_DOCUMENTO = R.ID_DOCUMENTO AND N.ID_TIPO_NOTA = 4 AND N.EFECTIVO = 1) AS LLAMADASEFECTIVAS 
FROM 
    GELEC.ED_RECLAMOS R  INNER JOIN GELEC.ED_DOCUMENTOS D ON D.ID_DOCUMENTO = R.ID_DOCUMENTO   
WHERE 
    1=1
--    R.FECHA_CREACION_CLIENTE BETWEEN TO_DATE (:FECHAINICIO, 'DD/MM/YYYY') AND TO_DATE (:FECHAFIN, 'DD/MM/YYYY')   
    AND R.FECHA_CREACION_CLIENTE BETWEEN TO_DATE ('20/12/2022', 'DD/MM/YYYY') AND TO_DATE ('28/12/2022', 'DD/MM/YYYY')   
ORDER BY 
    R.FECHA_CREACION_CLIENTE DESC