CREATE OR REPLACE VIEW NEXUS_GIS.DOCUMENT_EXTERNAL_DATA AS    
    SELECT 
        DET.DOCUMENT_ID, 
        DET.AFFECTED_COUNT,
        (SELECT MAX(LOG.FECHA_ACTUALIZACION) FROM NEXUS_GIS.WS_ENREMTAT_LOG LOG WHERE LOG.NRO_DOCUMENTO=DET.NRO_DOCUMENTO) LAST_DAY_MODIFICATION
    FROM (
        SELECT 
          DET.ID DOCUMENT_ID, 
          DET.NRO_DOCUMENTO,
          SUM(DET.CANT_AFECTACIONES) AFFECTED_COUNT
        FROM 
            NEXUS_GIS.TABLA_ENREMTAT_DET DET    
        WHERE 
            DET.ESTADO NOT IN('Cerrado','Cancelado')
        GROUP BY 
            DET.ID,
            DET.NRO_DOCUMENTO
    ) DET       
    UNION
    SELECT 
        B.DOCUMENT_ID, 
        B.AFFECTED_COUNT,
        (SELECT MAX(LOG.FECHA_LOG) FROM NEXUS_GIS.TABLA_ENRE_LOG LOG WHERE LOG.NRO_DOCUMENTO=B.NRO_DOCUMENTO) LAST_DAY_MODIFICATION
    FROM (  
        SELECT 
          D.ID DOCUMENT_ID,
          BT.NRO_DOCUMENTO,
          SUM(BT.CANTIDAD_EST_USU_AFECTADOS) AFFECTED_COUNT
        FROM 
            NEXUS_GIS.TABLA_ENRE BT,
            NEXUS_GIS.OMS_DOCUMENT D
        WHERE 
            D.NAME=BT.NRO_DOCUMENTO
            AND BT.ESTADO NOT IN('Cerrado','Cancelado')
        GROUP BY 
            D.ID,
            BT.NRO_DOCUMENTO
    ) B;



GRANT SELECT ON NEXUS_GIS.DOCUMENT_EXTERNAL_DATA TO NEXUSGIS_READ_ROLE;
 
GRANT SELECT ON NEXUS_GIS.DOCUMENT_EXTERNAL_DATA TO NEX_GIS01;










