SELECT 
    B.DOCUMENT_ID, 
    B.AFFECTED_COUNT,
    (SELECT MAX(FECHA_LOG) FROM NEXUS_GIS.TABLA_ENRE_LOG WHERE NRO_DOCUMENTO=B.NRO_DOCUMENTO) LAST_DAY_MODIFICATION
FROM (  
    SELECT 
      D.ID DOCUMENT_ID,
      BT.NRO_DOCUMENTO,
      SUM(BT.CANTIDAD_EST_USU_AFECTADOS) AFFECTED_COUNT
    FROM 
        NEXUS_GIS.TABLA_ENRE BT,
        NEXUS_GIS.OMS_DOCUMENT D
    WHERE 
        D.NAME=BT.NRO_DOCUMENTO
        AND BT.ESTADO NOT IN('Cerrado','Cancelado')
    GROUP BY 
        D.ID,
        BT.NRO_DOCUMENTO
) B
;

SELECT * FROM NEXUS_GIS.TABLA_ENRE;
SELECT * FROM NEXUS_GIS.TABLA_ENRE_LOG;
