SELECT 
    DET.DOCUMENT_ID, 
    DET.AFFECTED_COUNT,
    (SELECT MAX(FECHA_ACTUALIZACION) FROM NEXUS_GIS.WS_ENREMTAT_LOG WHERE NRO_DOCUMENTO=DET.NRO_DOCUMENTO) LAST_DAY_MODIFICATION
FROM (
    SELECT 
      DET.ID DOCUMENT_ID, 
      DET.NRO_DOCUMENTO,
      SUM(DET.CANT_AFECTACIONES) AFFECTED_COUNT
    FROM 
        NEXUS_GIS.TABLA_ENREMTAT_DET DET    
    WHERE 
        ESTADO NOT IN('Cerrado','Cancelado')
    GROUP BY 
        DET.ID,
        DET.NRO_DOCUMENTO
) DET       
;
  

SELECT * FROM NEXUS_GIS.TABLA_ENREMTAT_DET;
SELECT * FROM NEXUS_GIS.WS_ENREMTAT_LOG;
