select * from gelec.ed_documentos where nro_documento='D-21-11-024504'; --9738550
select * from GELEC.ed_det_documentos_clientes where id_documento=9738550;

select * from gelec.ed_documentos where nro_documento='D-22-08-004532'; 
select * from GELEC.ed_det_documentos_clientes where id_documento=10423407;


select * from gelec.ed_documentos where nro_documento='D-22-08-005468'; 
select * from GELEC.ed_det_documentos_clientes where id_documento=10415029;



select * from GELEC.ed_det_documentos_clientes where operacion='B' order by id_doc_cliente desc;

SELECT * FROM GELEC.ED_DOCUMENTOS WHERE ID_DOCUMENTO=9085316; --nro_documento='D-21-01-080502'; 
select * from gelec.ed_det_documentos_clientes where id_documento=9085316;
SELECT * FROM GELEC.ED_LOG;
SELECT FECHA_FIN_DOC FROM GELEC.ED_DOCUMENTOS WHERE ID_DOCUMENTO=9085316; --nro_documento='D-21-01-080502'; 
--UPDATE GELEC.ED_DOCUMENTOS SET FECHA_FIN_DOC=SYSDATE WHERE ID_DOCUMENTO=9084671;
--UPDATE GELEC.ED_DET_DOCUMENTOS_CLIENTES SET LOG_HASTA=NULL WHERE ID_DOC_CLIENTE=71221;
--COMMIT;
UPDATE GELEC.ED_DET_DOCUMENTOS_CLIENTES SET FECHA_FIN_CORTE=SYSDATE WHERE ID_DOCUMENTO=9085316 AND FECHA_FIN_CORTE IS NULL;
--
--CURSOR
SELECT CUENTA, ESTADO_CLIE, LOG_HASTA FROM GELEC.ED_DET_DOCUMENTOS_CLIENTES WHERE ID_DOCUMENTO = 9085316 AND LOG_HASTA IS NULL;
--DOC CERRADO EN GELEC
SELECT * FROM GELEC.ED_DOCUMENTOS WHERE ID_DOCUMENTO = 9085316 AND LOG_HASTA IS NULL;
SELECT COUNT (*) FROM GELEC.ED_DOCUMENTOS WHERE ID_DOCUMENTO = 9085316 AND LOG_HASTA IS NULL;
--DOC CERRADO EN OMS
SELECT ID, LAST_STATE_ID FROM NEXUS_GIS.OMS_DOCUMENT WHERE ID = 9085316; --AND LAST_STATE_ID < 5;
SELECT COUNT(1) FROM NEXUS_GIS.OMS_DOCUMENT WHERE ID = 9085316 AND LAST_STATE_ID < 5;



SELECT * FROM GELEC.ED_DOCUMENTOS WHERE FECHA_FIN_DOC IS NULL;













