SELECT 
  D.TIPO_CORTE, 
  D.FECHA, 
  COUNT(1) AS DOCUMENTOS,
  GELEC.CANTIDAD_RECLAMOS(D.FECHA, D.TIPO_CORTE) AS RECLAMOS,
  GELEC.CANTIDAD_LLAMADAS(D.FECHA, D.TIPO_CORTE) AS LLAMADAS,
  GELEC.CANTIDAD_LLAMADAS_EFECTIVAS(D.FECHA, D.TIPO_CORTE) AS LLAMADASEFECTIVAS
FROM (
    SELECT DISTINCT 
      DD.NRO_DOCUMENTO,
      DD.TIPO_CORTE,
      TO_CHAR (SYSDATE, 'dd/mm/yyyy') FECHA,
      TO_CHAR (DD.FECHA_INICIO_DOC, 'dd/mm/yyyy') AS FECHA_INICIO_DOC
    FROM 
      GELEC.ED_DOCUMENTOS DD,
      GELEC.ED_CLIENTE_NOTA CN, 
      GELEC.ED_NOTAS N
    WHERE
      1=1
      AND DD.ID_DOCUMENTO=CN.ID_DOCUMENTO
      AND CN.ID_NOTA=N.ID_NOTA 
      AND NVL(N.IDDESTINO,0)>0 
      AND TO_CHAR(N.FECHAHORA,'DD/MM/YYYY')= TO_CHAR(SYSDATE,'DD/MM/YYYY')
    UNION
    SELECT DISTINCT 
      D.NRO_DOCUMENTO,
      D.TIPO_CORTE,   
      TO_CHAR (SYSDATE, 'dd/mm/yyyy') FECHA,
      TO_CHAR (D.FECHA_INICIO_DOC, 'dd/mm/yyyy') AS FECHA_INICIO_DOC
    FROM 
      GELEC.ED_DOCUMENTOS d   
    WHERE 
      D.FECHA_INICIO_DOC BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE +1) 
) D
GROUP BY
    D.TIPO_CORTE,
    D.FECHA
ORDER BY
    D.TIPO_CORTE,
    D.FECHA
;