SELECT 
    O.CUENTA, 
    (SELECT REGION FROM GELEC.ED_CLIENTES WHERE CUENTA=O.CUENTA) REGION,
    (SELECT Z.ZONA FROM NEXUS_GIS.SPRCLIENTS S, NEXUS_GIS.PARTIDO_ZONA Z WHERE S.FSCLIENTID=O.CUENTA AND S.LEVELTWOAREAID=Z.AREAID) ZONA, 
    EF.SERIE, 
    EO.DESCRIPCION AS ESTADO, 
    O.INICIO, 
    O.FIN, 
    'ORD-'||TO_CHAR(O.INICIO,'YYYY-MM')||'-'||LPAD(O.ID,5,0) NRO_ORDEN,
    TI.DESCRIPCION AS TIPO, 
    FC.RETIRO, 
    FC.ID IDFAECLIENTE, 
    O.ABONADA,
    O.ID IDORDEN
From 
    GELEC.ED_ORDENES O 
    INNER JOIN GELEC.ED_FAE_CLIENTE FC ON FC.ID = O.ID_FAE_CLIENTE
    LEFT JOIN GELEC.ED_EQUIPO_FAE EF ON EF.ID = FC.ID_FAE
    INNER JOIN GELEC.ED_ESTADO_ORDENES EO ON EO.ID = O.ID_ESTADO
    INNER JOIN GELEC.ED_TIPO_ORDEN TI ON TI.ID = O.ID_TIPO 
WHERE 
    O.ID_ESTADO != 4
ORDER BY 
    O.CUENTA, 
    O.INICIO ASC
;
