--GEO
SELECT 'GEO' TIPO, O.OBJECTID, O.OBJECTNAMEID, O.SPRID, E.CAPTION, SL.LINKVALUE, SL.LINKID, L.LINKCAPTION
FROM 
    NEXUS_GIS.SPROBJECTS O, 
    NEXUS_GIS.SPRENTITIES E, 
    NEXUS_GIS.SPRLINKS SL, 
    NEXUS_GIS.LINKS L
WHERE 
    O.LOGIDTO=0
    AND O.OBJECTID=69376813
    AND O.SPRID=E.SPRID
    AND O.OBJECTID=SL.OBJECTID
    AND SL.LOGIDTO=0
    AND SL.LINKID=L.LINKID
;    
--UNI
SELECT 'UNI' TIPO, O.OBJECTID, O.OBJECTNAMEID, O.SPRID, E.CAPTION, SL.LINKVALUE, SL.LINKID, L.LINKCAPTION
FROM 
    NEXUS_GIS.SPROBJECTS O, 
    NEXUS_GIS.SPRENTITIES E, 
    NEXUS_GIS.SPRLINKS SL, 
    NEXUS_GIS.LINKS L
WHERE 
    O.LOGIDTO=0
--    AND O.OBJECTID=82964419
    AND O.SPRID=E.SPRID
    AND O.OBJECTID=SL.OBJECTID
    AND SL.LOGIDTO=0
    AND SL.LINKID=L.LINKID
    AND SL.LINKVALUE='19803-9                       '
; 
--TABLA
--SPRID 1163 Secc. B/C Tripolar MI MT         > LINKID 551 Número Elemento Maniobra GMT
--SPRID 1320 UNI MT Secc. Autodesconectador   > LINKID 1018 UNI Identificador Unico Gis

SELECT * FROM NEXUS_GIS.NUG_EM_GEOGRAFICO WHERE SPRID=1163;
SELECT * FROM NEXUS_GIS.NUG_EM_UNIFILAR WHERE SPRID=1320;
SELECT distinct id_tipo FROM NEXUS_GIS.NUG_EM_UNIFILAR;

