SELECT 
    D.TIPO_CORTE,
    D.FECHA,
    SUM(D.DOCUMENTOS) DOCUMENTOS,
    SUM(D.RECLAMOS) RECLAMOS,
    SUM(D.LLAMADAS) LLAMADAS,
    SUM(D.LLAMADAS_EFECTIVAS) LLAMADAS_EFECTIVAS
FROM (
        SELECT DISTINCT 
          DD.NRO_DOCUMENTO,
          DD.TIPO_CORTE,
          TO_CHAR (SYSDATE, 'dd/mm/yyyy') FECHA,
          TO_CHAR (DD.FECHA_INICIO_DOC, 'dd/mm/yyyy') AS FECHA_INICIO_DOC, 
          1 DOCUMENTOS, 
          (SELECT COUNT(1) FROM GELEC.ED_RECLAMOS WHERE ID_DOCUMENTO=DD.ID_DOCUMENTO) RECLAMOS, 
          (SELECT COUNT(1) FROM GELEC.ED_CLIENTE_NOTA CN, GELEC.ED_NOTAS N WHERE CN.ID_NOTA=N.ID_NOTA AND NVL(N.IDDESTINO,0)>0 AND CN.ID_DOCUMENTO=DD.ID_DOCUMENTO AND TO_CHAR(N.FECHAHORA,'DD/MM/YYYY')= TO_CHAR(SYSDATE,'DD/MM/YYYY')) LLAMADAS, 
          (SELECT COUNT(1) FROM GELEC.ED_CLIENTE_NOTA CN, GELEC.ED_NOTAS N WHERE CN.ID_NOTA=N.ID_NOTA AND NVL(N.IDDESTINO,0)>0 AND NVL(N.EFECTIVO,0)>0 AND CN.ID_DOCUMENTO=DD.ID_DOCUMENTO AND TO_CHAR(N.FECHAHORA,'DD/MM/YYYY')= TO_CHAR(SYSDATE,'DD/MM/YYYY')) LLAMADAS_EFECTIVAS
        FROM 
          GELEC.ED_DOCUMENTOS DD,
          GELEC.ED_CLIENTE_NOTA CN, 
          GELEC.ED_NOTAS N
        WHERE
          1=1
          AND DD.ID_DOCUMENTO=CN.ID_DOCUMENTO
          AND CN.ID_NOTA=N.ID_NOTA 
          AND NVL(N.IDDESTINO,0)>0 
          AND TO_CHAR(N.FECHAHORA,'DD/MM/YYYY')= TO_CHAR(SYSDATE,'DD/MM/YYYY')
          
        UNION
        
        SELECT DISTINCT 
          DD.NRO_DOCUMENTO,
          DD.TIPO_CORTE,   
          TO_CHAR (SYSDATE, 'dd/mm/yyyy') FECHA,
          TO_CHAR (DD.FECHA_INICIO_DOC, 'dd/mm/yyyy') AS FECHA_INICIO_DOC, 
          1 DOCUMENTOS, 
          (SELECT COUNT(1) FROM GELEC.ED_RECLAMOS WHERE ID_DOCUMENTO=DD.ID_DOCUMENTO) RECLAMOS, 
          (SELECT COUNT(1) FROM GELEC.ED_CLIENTE_NOTA CN, GELEC.ED_NOTAS N WHERE CN.ID_NOTA=N.ID_NOTA AND NVL(N.IDDESTINO,0)>0 AND CN.ID_DOCUMENTO=DD.ID_DOCUMENTO) LLAMADAS, 
          (SELECT COUNT(1) FROM GELEC.ED_CLIENTE_NOTA CN, GELEC.ED_NOTAS N WHERE CN.ID_NOTA=N.ID_NOTA AND NVL(N.IDDESTINO,0)>0 AND NVL(N.EFECTIVO,0)>0 AND CN.ID_DOCUMENTO=DD.ID_DOCUMENTO) LLAMADAS_EFECTIVAS
        FROM 
          GELEC.ED_DOCUMENTOS DD
        WHERE 
          DD.FECHA_INICIO_DOC BETWEEN TRUNC(SYSDATE) AND TRUNC(SYSDATE +1) 
    ) D
GROUP BY
    D.TIPO_CORTE,
    D.FECHA
ORDER BY
    D.TIPO_CORTE
        ;
