DEFINE FECHAINICIO= TO_CHAR('01/08/2022');
DEFINE FECHAFIN= TO_CHAR('10/08/2022');

Select 
    D.NRO_DOCUMENTO AS NRODOCUMENTO, 
    R.CUENTA, 
    R.NOMBRE, 
    R.FECHA_CREACION_CLIENTE AS FECHA, 
    NVL(R.REITERACIONES,0) AS REITERACIONES,
    R.ULTIMA_REITERACION AS ULTIMAREITERACION, 
    R.FECHA_CIERRE FECHA_FIN_RECLAMO,
    D.REGION, 
    D.ZONA, 
    D.PARTIDO, 
    D.LOCALIDAD,
    (SELECT COUNT(*) FROM GELEC.ED_CLIENTE_NOTA CN INNER JOIN GELEC.ED_NOTAS N ON N.ID_NOTA = CN.ID_NOTA WHERE CN.CUENTA = R.CUENTA AND CN.ID_DOCUMENTO = R.ID_DOCUMENTO AND N.ID_TIPO_NOTA = 4 AND N.EFECTIVO IS NOT NULL) AS LLAMADAS, 
    (select count(*) from GELEC.ED_CLIENTE_NOTA cn inner join GELEC.ED_NOTAS n on n.ID_NOTA = cn.ID_NOTA  where cn.CUENTA = r.cuenta and cn.ID_DOCUMENTO = r.id_documento and n.ID_TIPO_NOTA = 4 and n.EFECTIVO = 1) as llamadasEfectivas 
FROM 
    GELEC.ED_RECLAMOS r inner join GELEC.ED_DOCUMENTOS d on d.ID_DOCUMENTO = r.ID_DOCUMENTO   
WHERE 
--    R.FECHA_CREACION_CLIENTE BETWEEN TO_DATE (:FECHAINICIO, 'DD/MM/YYYY') AND TO_DATE (:FECHAFIN, 'DD/MM/YYYY') 
    R.FECHA_CREACION_CLIENTE BETWEEN TO_DATE (&FECHAINICIO, 'DD/MM/YYYY') AND TO_DATE (&FECHAFIN, 'DD/MM/YYYY') 
ORDER BY 
    R.FECHA_CREACION_CLIENTE DESC
;