--D-22-04-008922
SELECT * FROM NEXUS_GIS.TABLA_ENREMTAT_GEN WHERE NRO_DOCUMENTO='D-22-04-008922';
-- se inserto en GEN

SELECT * FROM NEXUS_GIS.TABLA_ENREMTAT_DET WHERE NRO_DOCUMENTO='D-22-04-008922';
-- no se inserto en det

SELECT  NVL(D.COUNT_INIT_AFFECTED_CUSTOMERS, D.AFFECTED_CLIENTS) AS COUNT_AFFECTED FROM NEXUS_GIS.OMS_DOCUMENT D WHERE D.NAME='D-22-04-008922';
--SIN AFECTACIONES AL INICIO!
--por este motivo no se pudo insertar en la tabla det, y por tal motivo no se informo al enre. 

SELECT AFFECTED_CLIENTS FROM NEXUS_GIS.OMS_DOCUMENT WHERE NAME='D-22-04-008922';
--AFFECTED_CLIENTS EN CERO..

--CONCLUSION: CUANDO RECORRE LOS DOCUMENTOS ACTIVOS DE LA TABLA GEN, BUSCA LAS AFECTACIONES AL INICIO EN OMS_DOCUMENT, SI ESTA DEVUELVE NULL, ENTONCES BUSCA AFFECTED_CLIENTS DE LA MISMA TABLA... ESTE VALOR ES EL PRIMER FILTRO EN ESTE PROCESO. 


