SELECT 
  T.*
FROM (  
  SELECT 
      C.CUENTA,
      CC.ID_TEL,
      CC.TELEFONO, 
      COUNT(N.ID_NOTA) LLAMADAS, 
      SUM(NVL(N.EFECTIVO,0)) EFECTIVAS
  FROM 
      GELEC.ED_CLIENTES C, 
      GELEC.ED_CONTACTOS_CLIENTES CC,
      GELEC.ED_NOTAS N
  WHERE
      NVL(C.LOG_HASTA,0)=0
      AND NVL(CC.LOG_HASTA,0)=0
      AND C.CUENTA=CC.CUENTA
      AND CC.ID_TEL=N.IDDESTINO(+)
  GROUP BY
      C.CUENTA,
      CC.ID_TEL,
      CC.TELEFONO
) T
ORDER BY T.CUENTA, T.LLAMADAS DESC
;

SELECT * FROM GELEC.ED_CONTACTOS_CLIENTES;
SELECT * FROM GELEC.ED_NOTAS;


SELECT 
    C.CUENTA,
    COUNT(N.ID_NOTA) LLAMADAS, 
    SUM(NVL(N.EFECTIVO,0)) EFECTIVAS,
    CASE WHEN (SELECT COUNT(1) FROM GELEC.ED_MARCA_CLIENTE WHERE CUENTA=C.CUENTA AND ID_MARCA=1)=1 THEN 'Si' ELSE 'No' END BAJA_POTENCIAL
FROM 
    GELEC.ED_CLIENTES C, 
    GELEC.ED_CONTACTOS_CLIENTES CC,
    GELEC.ED_NOTAS N
WHERE
    NVL(C.LOG_HASTA,0)=0
    AND NVL(CC.LOG_HASTA,0)=0
    AND C.CUENTA=CC.CUENTA
    AND CC.ID_TEL=N.IDDESTINO(+)
GROUP BY
    C.CUENTA
HAVING
    COUNT(N.ID_NOTA)=0



