--NECOPER-163 GELEC - Reporte de Clientes sin contacto telf + Clientes sin telef asociado

SELECT * FROM ALL_TABLES 
WHERE OWNER='GELEC' 
    AND TABLE_NAME NOT LIKE '%FAE%'
    AND TABLE_NAME NOT LIKE '%MARCA%'
    AND TABLE_NAME NOT LIKE '%BATCH%'
    AND TABLE_NAME NOT LIKE '%DICC%'
    AND TABLE_NAME NOT LIKE '%LOG%'
    AND TABLE_NAME NOT LIKE '%ARTEF%'
    AND TABLE_NAME NOT LIKE '%DOCU%'
    AND TABLE_NAME NOT LIKE '%MARCA%'
    AND TABLE_NAME NOT LIKE '%MARCA%'
;
/*
SELECT * FROM GELEC.ED_CLIENTES;
SELECT * FROM GELEC.ED_PARTIDO_ZONA;
*/
SELECT * FROM GELEC.ED_CLIENTES;
SELECT * FROM GELEC.ED_NOTAS ORDER BY ID_NOTA DESC;
SELECT * FROM GELEC.ED_NOTAS WHERE IDDESTINO=4246;
SELECT * FROM GELEC.ED_CLIENTE_NOTA;
SELECT * FROM GELEC.ED_CONTACTOS_CLIENTES;
SELECT * FROM GELEC.ED_CONTACTOS_CLIENTES WHERE ID_TEL=14938;
SELECT FSCLIENTID, CUSTATT16, CUSTATT21 FROM NEXUS_GIS.SPRCLIENTS WHERE FSCLIENTID='6245164564';

--clientes que nunca se pudo tener contacto

SELECT 
    T.*, 
    (SELECT MAX(FECHAHORA) FROM GELEC.ED_NOTAS WHERE IDDESTINO=T.ID_TEL AND NVL(EFECTIVAS,0)>0) ULTIMO_CONTACTO_EFECTIVO, 
    (CASE WHEN (SELECT COUNT(1) FROM GELEC.ED_CONTACTOS_CLIENTES WHERE ID_TEL=T.ID_TEL AND NVL(LOG_HASTA,0)=0)>0 THEN 'ACTIVO' ELSE 'BAJA' END) ESTADO_TELEFONO,
    (CASE WHEN (SELECT COUNT(1) FROM NEXUS_GIS.SPRCLIENTS WHERE FSCLIENTID=T.CUENTA AND CUSTATT21='12521') = 1 THEN 'EDP' ELSE 'BC' END) ESTADO_CLIENTE
FROM (
    SELECT 
        C.CUENTA,
        CC.ID_TEL, 
        CC.TELEFONO, 
        SUM(CASE WHEN NVL(N.EFECTIVO,-1)>=0 THEN 1 ELSE 0 END) LLAMADAS, 
        SUM(CASE WHEN NVL(N.EFECTIVO,0)>0 THEN 1 ELSE 0 END) EFECTIVAS
    FROM 
        GELEC.ED_CLIENTES C,
        GELEC.ED_CONTACTOS_CLIENTES CC,
        GELEC.ED_NOTAS N
    WHERE
        1=1
        AND C.CUENTA=CC.CUENTA(+)
        AND CC.ID_TEL=N.IDDESTINO(+)
    GROUP BY
        C.CUENTA, 
        CC.ID_TEL, 
        CC.TELEFONO
    ORDER BY
        C.CUENTA, 
        CC.ID_TEL DESC
) T

;














SELECT 
    C.CUENTA,
    CC.ID_TEL, 
    CC.TELEFONO, 
    SUM(CASE WHEN NVL(N.EFECTIVO,-1)>=0 THEN 1 ELSE 0 END) LLAMADAS, 
    SUM(CASE WHEN NVL(N.EFECTIVO,0)>0 THEN 1 ELSE 0 END) EFECTIVAS, 
    (CASE WHEN NVL(CC.LOG_HASTA,0)=0 THEN 'Activo' ELSE 'Inactivo' END) ESTADO_TELEFONO, 
    (CASE WHEN S.CUSTATT21=12521 THEN 'EDP' ELSE 'BC' END) ESTADO_CLIENTE
FROM 
    GELEC.ED_CLIENTES C,
    GELEC.ED_CONTACTOS_CLIENTES CC,
    GELEC.ED_NOTAS N,
    NEXUS_GIS.SPRCLIENTS S
WHERE
    1=1
    AND C.CUENTA=CC.CUENTA(+)
    AND CC.ID_TEL=N.IDDESTINO(+)
    AND C.CUENTA=S.FSCLIENTID
GROUP BY
    C.CUENTA, 
    CC.ID_TEL, 
    CC.TELEFONO, 
    (CASE WHEN NVL(CC.LOG_HASTA,0)=0 THEN 'Activo' ELSE 'Inactivo' END),
    (CASE WHEN S.CUSTATT21=12521 THEN 'EDP' ELSE 'BC' END) 
ORDER BY
    C.CUENTA, 
    CC.ID_TEL DESC
;


--clientes que no tienen teléfonos asociados
SELECT 
  C.CUENTA, C.RAZON_SOCIAL, 
  (CASE WHEN (SELECT COUNT(1) FROM NEXUS_GIS.SPRCLIENTS WHERE FSCLIENTID=C.CUENTA AND CUSTATT21='12521') = 1 THEN 'ACTIVO' ELSE 'BAJA' END) ESTADO, 
  C.CALLE, C.NRO, C.PISO_DPTO, 
  C.LOCALIDAD, C.PARTIDO, C.REGION, 
  C.SSEE, C.ALIMENTADOR, C.CT
FROM GELEC.ED_CLIENTES C WHERE CUENTA NOT IN (SELECT CUENTA FROM GELEC.ED_CONTACTOS_CLIENTES)
ORDER BY ESTADO
;






--
SELECT * FROM GELEC.ED_NOTAS;
SELECT * FROM GELEC.ED_CLIENTE_NOTA;
SELECT * FROM GELEC.ED_SUBTIPO_NOTA;
SELECT * FROM GELEC.ED_DET_DOCUMENTOS_CLIENTES_AUD;
SELECT * FROM GELEC.ED_BATCH_LOG;
SELECT * FROM GELEC.ED_DICCIONARIO_APARATOLOGIA;
SELECT * FROM GELEC.ED_MODELO_FAE;
SELECT * FROM GELEC.ED_FAE_DEPOSITOS;
SELECT * FROM GELEC.TEMPORAL_CLIENTE_NOTA;
SELECT * FROM GELEC.ED_MARCA_CLIENTE;
SELECT * FROM GELEC.ED_EQUIPO_FAE;
SELECT * FROM GELEC.ED_ESTADO_FAE;
SELECT * FROM GELEC.ED_LOG;
SELECT * FROM GELEC.ED_FAE_CLIENTE;
SELECT * FROM GELEC.ED_CLIENTE_ARTEFACTO;
SELECT * FROM GELEC.ED_MARCAS;
SELECT * FROM GELEC.ED_AMAREAS;
SELECT * FROM GELEC.ED_CONTRATISTAS;
SELECT * FROM GELEC.ED_HISTORIAL_NOVEDADES;
SELECT * FROM GELEC.ED_SUBTIPO_NOTA;
SELECT * FROM GELEC.ED_ARTEFACTOS;
SELECT * FROM GELEC.ED_PACIENTE_CLIENTE;
SELECT * FROM GELEC.ED_TIPO_NOTA;
SELECT * FROM GELEC.ED_ESTADO_ORDENES;
SELECT * FROM GELEC.ED_CLIENTE_NOTA;
SELECT * FROM GELEC.ED_AGENDA;
SELECT * FROM GELEC.ED_DET_DOCUMENTOS_CLIENTES_AUD;
SELECT * FROM GELEC.ED_CLIENTES;
SELECT * FROM GELEC.ED_TIPO_RECLAMO;
SELECT * FROM GELEC.ED_ORDENES;
SELECT * FROM GELEC.ED_SUBMARCAS;
SELECT * FROM GELEC.ED_AUDITORIA;
SELECT * FROM GELEC.ED_PARTIDO_ZONA;
SELECT * FROM GELEC.AUX;
SELECT * FROM GELEC.ED_TIPO_ORDEN;
SELECT * FROM GELEC.ED_RECLAMOS;
SELECT * FROM GELEC.ED_DOCUMENTOS;
SELECT * FROM GELEC.ED_TIEMPO_ARTEFACTOS;
SELECT * FROM GELEC.ED_DOCUMENTO_ANOMALIA;
