    SELECT 
        T.*, 
        (SELECT MAX(FECHAHORA) FROM GELEC.ED_NOTAS WHERE IDDESTINO=T.ID_TEL AND NVL(EFECTIVAS,0)>0) ULTIMO_CONTACTO_EFECTIVO, 
        (CASE WHEN (SELECT COUNT(1) FROM GELEC.ED_CONTACTOS_CLIENTES WHERE ID_TEL=T.ID_TEL AND NVL(LOG_HASTA,0)=0)>0 THEN 'ACTIVO' ELSE 'BAJA' END) ESTADO_TELEFONO,
        (CASE WHEN (SELECT COUNT(1) FROM NEXUS_GIS.SPRCLIENTS WHERE FSCLIENTID=T.CUENTA AND CUSTATT21='12521') = 1 THEN 'EDP' ELSE 'BC' END) ESTADO_CLIENTE
    FROM (
        SELECT 
            C.CUENTA,
            CC.ID_TEL, 
            CC.TELEFONO, 
            SUM(CASE WHEN NVL(N.EFECTIVO,-1)>=0 THEN 1 ELSE 0 END) LLAMADAS, 
            SUM(CASE WHEN NVL(N.EFECTIVO,0)>0 THEN 1 ELSE 0 END) EFECTIVAS
        FROM 
            GELEC.ED_CLIENTES C,
            GELEC.ED_CONTACTOS_CLIENTES CC,
            GELEC.ED_NOTAS N
        WHERE
            1=1
            AND C.CUENTA=CC.CUENTA(+)
            AND CC.ID_TEL=N.IDDESTINO(+)
        GROUP BY
            C.CUENTA, 
            CC.ID_TEL, 
            CC.TELEFONO
        ORDER BY
            C.CUENTA, 
            CC.ID_TEL DESC
    ) T