SET SERVEROUTPUT ON
DECLARE
    CURSOR C_DATOS IS (
        SELECT DC.ID_DOCUMENTO, DC.CUENTA, DC.CT_CLIE, DC.FECHA_INICIO_CORTE, DC.FECHA_FIN_CORTE
        FROM GELEC.ED_DET_DOCUMENTOS_CLIENTES DC
        WHERE DC.FECHA_INICIO_CORTE>DC.FECHA_FIN_CORTE
        --ORDER BY ID_DOCUMENTO, CUENTA
--        AND ROWNUM<2
    );
    
    V_FECHA GELEC.ED_DET_DOCUMENTOS_CLIENTES.FECHA_INICIO_CORTE%TYPE;
    V_ID NUMBER;
    V_DUPLICADOS NUMBER;

BEGIN
    FOR F_DATOS IN C_DATOS LOOP
        
        DBMS_OUTPUT.PUT_LINE('DOCUMENTO>'||F_DATOS.ID_DOCUMENTO);
        DBMS_OUTPUT.PUT_LINE('CUENTA>'||F_DATOS.CUENTA);
        DBMS_OUTPUT.PUT_LINE('CT>'||F_DATOS.CT_CLIE);
        DBMS_OUTPUT.PUT_LINE('FECHA_INICIO_CORTE>'||F_DATOS.FECHA_INICIO_CORTE);
        DBMS_OUTPUT.PUT_LINE('FECHA_FIN_CORTE>'||F_DATOS.FECHA_FIN_CORTE);
        
        V_FECHA:= F_DATOS.FECHA_INICIO_CORTE;
        
        FOR F_FECHAS IN (
            SELECT * FROM NEXUS_GIS.OMS_AFFECT_RESTORE_OPERATION WHERE DOCUMENT_ID=F_DATOS.ID_DOCUMENTO AND LAST_MODIFIED_DATE= V_FECHA AND IS_RESTORE=0 AND OPERATION_ID IS NOT NULL
        ) LOOP
        
          --BUSCO EL ID DE AFECTACION
          SELECT AE.ID
          INTO V_ID
          FROM 
            NEXUS_GIS.OMS_AFFECTED_ELEMENT AE, 
            NEXUS_GIS.SPROBJECTS O, 
            nexus_gis.sprlinks s
          WHERE 
            AE.AFFECT_ID=F_FECHAS.ID
            and AE.ELEMENT_ID=O.OBJECTNAMEID
            AND O.LOGIDTO=0
            AND O.OBJECTID= S.OBJECTID
            AND S.LINKID=1018
            and linkvalue like F_DATOS.CT_CLIE||'%'
            ;
        
            DBMS_OUTPUT.PUT_LINE('ID AFECTACION>'||V_ID);
            DBMS_OUTPUT.PUT_LINE('INICIO>'||F_FECHAS.TIME);
            
            --DESDE EL ID DE AFECTACION BUSCO LA FECHA DE RESTAURACION
            SELECT ARO.LAST_MODIFIED_DATE INTO V_FECHA FROM NEXUS_GIS.OMS_AFFECT_RESTORE_OPERATION ARO, NEXUS_GIS.OMS_AFFECTED_ELEMENT AE WHERE ARO.ID=AE.RESTORE_ID AND AE.ID=V_ID;
            
            DBMS_OUTPUT.PUT_LINE('FIN>'||V_FECHA);
            
            --DESDE LA FECHA DE RESTAURACION, CONSULTO DUPLICADOS
            SELECT COUNT(1) INTO V_DUPLICADOS FROM GELEC.ED_DET_DOCUMENTOS_CLIENTES WHERE ID_DOCUMENTO= F_DATOS.ID_DOCUMENTO AND CUENTA=F_DATOS.CUENTA AND FECHA_FIN_CORTE=V_FECHA;
            
            DBMS_OUTPUT.PUT_LINE('DUPLICADOS>'||V_DUPLICADOS);
            
        
        END LOOP;
        
        
        DBMS_OUTPUT.PUT_LINE('----------------------------------------------');
    end loop;

end;