--NECOPER-181 TODOS LOS CLIENTES, TODOS LOS TELEFONOS, Y SU EFECTIVIDAD. 

    SELECT 
        C.CUENTA, 
        C.RAZON_SOCIAL NOMBRE, 
        T.TELEFONO, 
        T.TIPO_CONTACTO TIPO, 
        NVL(SUM(N.EFECTIVO),0) EFECTIVO
    FROM 
        GELEC.ED_CLIENTES C, 
        GELEC.ED_CONTACTOS_CLIENTES T,
        GELEC.ED_NOTAS N
    WHERE
      C.CUENTA=T.CUENTA
      AND C.F_BAJA IS NULL
      AND NVL(T.LOG_HASTA,0)=0
      AND T.ID_TEL=N.IDDESTINO(+)
    GROUP BY
      C.CUENTA, C.RAZON_SOCIAL, T.TELEFONO, T.TIPO_CONTACTO
    ORDER BY
      C.CUENTA, NVL( SUM(N.EFECTIVO),0) DESC;