    SELECT DISTINCT
        D.ID
        ,D.NAME
        ,L.LINKVALUE
        ,L.LINKID
        ,CASE WHEN AE.LAST_MODIFIED_DATE IS NULL THEN D.CREATION_TIME ELSE AE.LAST_MODIFIED_DATE END LAST_MODIFIED_DATE        
    FROM
        NEXUS_GIS.OMS_DOCUMENT D
        ,NEXUS_GIS.OMS_AFFECT_RESTORE_OPERATION ARO
        ,NEXUS_GIS.OMS_AFFECTED_ELEMENT AE
        ,NEXUS_GIS.SPROBJECTS O
        ,NEXUS_GIS.SPRLINKS L
    WHERE
        1=1
        AND D.ID=ARO.DOCUMENT_ID
        AND ARO.ID=AE.AFFECT_ID
        AND AE.ELEMENT_ID=O.OBJECTNAMEID
        AND O.OBJECTID=L.OBJECTID
        AND D.LAST_STATE_ID IN (1,2,3,4)
        AND D.TYPE_ID IN (1,2)
        AND O.LOGIDTO=0
        AND L.LOGIDTO=0
        AND L.LINKID=407
    ;