    SELECT 
        ARO.DOCUMENT_ID
        ,D.NAME
        ,SUM(AE.COUNT_PROPERTIES) AFFECTED_COUNT
        ,CASE WHEN AE.LAST_MODIFIED_DATE IS NULL THEN D.CREATION_TIME ELSE AE.LAST_MODIFIED_DATE END LAST_MODIFIED_DATE
        ,D.TYPE_ID
    FROM
        NEXUS_GIS.OMS_DOCUMENT D
        ,NEXUS_GIS.OMS_AFFECT_RESTORE_OPERATION ARO
        ,NEXUS_GIS.OMS_AFFECTED_ELEMENT AE
    WHERE
        D.LAST_STATE_ID IN (1,2,3,4)
        AND D.ID=ARO.DOCUMENT_ID
        AND ARO.ID=AE.AFFECT_ID
        AND D.TYPE_ID IN (3,4,5,6)
    GROUP BY
        ARO.DOCUMENT_ID
        ,D.NAME
        ,CASE WHEN AE.LAST_MODIFIED_DATE IS NULL THEN D.CREATION_TIME ELSE AE.LAST_MODIFIED_DATE END 
        ,D.TYPE_ID    
    ;    