SET SERVEROUTPUT ON
declare

    V_EXISTE NUMBER;
    
begin

    SELECT COUNT(1) INTO V_EXISTE FROM ALL_TABLES WHERE OWNER='GELEC' AND TABLE_NAME = 'ED_CLIENTES_MANUALES';
    
    IF V_EXISTE=0 THEN
        DBMS_OUTPUT.PUT_LINE('GELEC.ED_CLIENTES_MANUALES: no existe.');
        
        EXECUTE IMMEDIATE
            'CREATE TABLE GELEC.ED_CLIENTES_MANUALES
              as (SELECT CUENTA, F_ALTA F_LIMITE, LOG_DESDE, LOG_HASTA FROM GELEC.ED_CLIENTES WHERE CUENTA=1)';
        
        DBMS_OUTPUT.PUT_LINE('GELEC.ED_CLIENTES_MANUALES: Se creo la tabla.');
        
    ELSE
        DBMS_OUTPUT.PUT_LINE('GELEC.ED_CLIENTES_MANUALES: Tabla existe.');
    END IF;

end;

